openapi: 3.0.0
info:
  title: Transfers Indexer API
  description: API documentation for the Transfers Indexer, detailing how to fetch MAS token transfers.
  version: '1.0.0'
servers:
  - url: http://localhost:4444/
paths:
  /last_slot:
    get:
      summary: Get the last slot written to DB
      description: Get the last slot written to DB
      responses:
        '200':
          description: The slot
          content:
            application/json:
              examples:
                example-1:
                  value:
                    ["275779_0"]
  /transfers:
    get:
      summary: Fetch transfers
      description: Fetches all the transfers based on the provided criteria (address, operation ID, date range).
      parameters:
        - name: from
          in: query
          description: Fetching all the transfers from a specified address.
          required: false
          schema:
            type: string
          example: AU12QxhhkrkGxewQ7vqkggsj81uchT1r3Qq1Hvn21rUXFQ94h1Nnv
        - name: to
          in: query
          description: Fetching all the transfers to a specified address.
          required: false
          schema:
            type: string
          example: AU12QxhhkrkGxewQ7vqkggsj81uchT1r3Qq1Hvn21rUXFQ94h1Nnv
        - name: operation_id
          in: query
          description: Fetching all the transfers made in an operation.
          required: false
          schema:
            type: string
          example: O12K6AwRg7jnDP4XvDazuH3j19KNK1FzuHuN9oNgACdMfhJJH9XM
        - name: succeed
          in: query
          description: Fetching all the transfers that succeeded
          required: false
          schema:
            type: string
          example: true
        - name: start_date
          in: query
          description: Start date for fetching transfers within a specific date range.
          required: false
          schema:
            type: string
            format: date-time
          example: 2024-02-20T02:00:00Z
        - name: end_date
          in: query
          description: End date for fetching transfers within a specific date range.
          required: false
          schema:
            type: string
            format: date-time
          example: 2024-02-21T00:00:00Z
      responses:
        '200':
          description: An array of transfer objects.
          content:
            application/json:
              examples:
                example-1:
                  value:
                    - from: "AU1Fp7uBP2TXxDty2HdTE3ZE3XQ4cNXnG3xuo8TkQLJtyxC7FKhx"
                      to: "AU1iUsXqfqAfhBw7Bc4yMm2nw3AzLdo9f6bsMTm7no3UZpzBvuNR"
                      amount: "0.000000001"
                      succeed: false
                      fee: "0.000000001"
                      block_id: "B1c5HYaFtVozAu2mKhr1XrVcvse5Ffwt2feew6RmPoHkWgc1BGx"
                      operation_time: "2024-02-28T12:49:38.000000000"
                      context: 
                        operation_id: "O12Bve9WYNApCDCcJFGy4giJSNTzhEBVoTtyxDFWxMFYF1iJYYbd"
                    - from: "AU1Fp7uBP2TXxDty2HdTE3ZE3XQ4cNXnG3xuo8TkQLJtyxC7FKhx"
                      to: "AU12FoGv3tAQ7pbMVZFL5TRnVwmSGDYcb69vGbG8s9cppSFVAER6n"
                      amount: "0.000000001"
                      succeed: false,
                      fee: "0.000000001"
                      block_id: "B1c5HYaFtVozAu2mKhr1XrVcvse5Ffwt2feew6RmPoHkWgc1BGx"
                      operation_time: "2024-02-28T12:49:38.000000000"
                      context: 
                        operation_id: "O12uZnkLMsmeiCJpgkP6agX5VYTvsNp7xdNLs3ew5Wrp6ytfiPdZ"
